name: Bump Dependencies

on:
  repository_dispatch:
    types: [bump-dependencies]

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: plumpy/bumpdep@master
        with:
          tag: ${{ github.ref }}
          key: korkVersion
          repositories: fiat,echo
          repoOwner: plumpy
          upstreamOwner: plumpy
          reviewers: ''
