name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: plumpy/bumpdep@master
      with:
        tag: ${{ github.ref }}
        key: korkVersion
        repositories: fiat,echo
        repoOwner: plumpy
        upstreamOwner: plumpy
        reviewers: ''
